/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Geometry conformance for the shipped app-icon assets.
 *
 * These do not render an icon — they assert the structural properties macOS,
 * Windows and browsers rely on when they draw one. Each assertion maps to a
 * specific way an icon visibly breaks:
 *
 *   opaque corners      the macOS Dock does not mask icons, so an opaque
 *                       canvas renders as a square tile beside every correctly
 *                       built neighbour
 *   wrong body fraction Apple's grid puts the body at 824/1024; a full-bleed
 *                       icon renders visibly larger than its neighbours
 *   missing .icns size  macOS picks a member per context (Dock, Finder, Cmd-Tab,
 *                       Get Info) and per display scale. A missing member is
 *                       upscaled from a smaller one and looks soft — which is
 *                       why every documented member is asserted rather than
 *                       just the largest.
 *
 * The assets are generated by `scripts/generate-brand-icons.mjs`. This file
 * parses the committed binaries directly — no `iconutil`, no network — so it
 * runs the same on Linux CI as on a developer's Mac.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { describe, expect, it } from 'vitest';

const projectRoot = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf-8' }).trim();
const asset = (rel: string) => path.join(projectRoot, rel);

/** Apple Big Sur icon grid: body 824 of 1024, corner radius 22.5% of the body. */
const APPLE_BODY_FRACTION = 824 / 1024;
/** Rounding at small sizes moves the fraction by a few percent; 128px lands at 81.3%. */
const BODY_FRACTION_TOLERANCE = 0.02;

type Geometry = {
  width: number;
  height: number;
  cornerAlpha: number[];
  bodyFraction: number;
  transparentRatio: number;
};

async function measure(input: Buffer | string): Promise<Geometry> {
  const { data, info } = await sharp(input).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;
  const alphaAt = (x: number, y: number) => data[(y * width + x) * channels + 3];

  let minX = width;
  let maxX = -1;
  let minY = height;
  let maxY = -1;
  let transparent = 0;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const a = alphaAt(x, y);
      if (a < 250) transparent++;
      if (a > 8) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }

  return {
    width,
    height,
    cornerAlpha: [alphaAt(0, 0), alphaAt(width - 1, 0), alphaAt(0, height - 1), alphaAt(width - 1, height - 1)],
    bodyFraction: (maxX - minX + 1) / width,
    transparentRatio: transparent / (width * height),
  };
}

/**
 * Splits an `.icns` container into its members.
 * Format: `icns` + total length, then chunks of 4-byte type + 4-byte length
 * (length includes the 8-byte header).
 */
function parseIcns(buf: Buffer): Map<string, Buffer> {
  expect(buf.toString('ascii', 0, 4)).toBe('icns');
  expect(buf.readUInt32BE(4)).toBe(buf.length);

  const members = new Map<string, Buffer>();
  let offset = 8;
  while (offset + 8 <= buf.length) {
    const type = buf.toString('ascii', offset, offset + 4);
    const length = buf.readUInt32BE(offset + 4);
    expect(length).toBeGreaterThanOrEqual(8);
    members.set(type, buf.subarray(offset + 8, offset + length));
    offset += length;
  }
  expect(offset).toBe(buf.length);
  return members;
}

/** Sizes each PNG-encoded `.icns` member must decode to. */
const ICNS_PNG_MEMBERS: Array<[string, number, string]> = [
  ['ic11', 32, '16pt @2x — menu bar, Cmd-Tab on Retina'],
  ['ic12', 64, '32pt @2x — Finder list view on Retina'],
  ['ic07', 128, '128pt — Finder icon view'],
  ['ic13', 256, '128pt @2x — Finder icon view on Retina'],
  ['ic08', 256, '256pt — Get Info'],
  ['ic14', 512, '256pt @2x — Get Info on Retina'],
  ['ic09', 512, '512pt — Dock at large sizes'],
  ['ic10', 1024, '512pt @2x — Dock at large sizes on Retina'],
];

/** Full-bleed targets: rounded corners, but no margin — these platforms add none. */
const FULL_BLEED = [
  ['resources/app.png', 1024, 'Linux desktop entry'],
  ['resources/icon.png', 800, 'generic app icon'],
  ['public/pwa/icon-180.png', 180, 'apple-touch-icon'],
  ['public/pwa/icon-192.png', 192, 'PWA manifest'],
  ['public/pwa/icon-512.png', 512, 'PWA manifest'],
  ['packages/desktop/src/renderer/assets/logos/brand/app.png', 1024, 'in-app brand mark'],
] as const;

describe('macOS .icns', () => {
  const icns = parseIcns(readFileSync(asset('resources/app.icns')));

  it('carries every member macOS selects between', () => {
    for (const [type, , context] of ICNS_PNG_MEMBERS) {
      expect(icns.has(type), `missing ${type} (${context})`).toBe(true);
    }
    // 16pt and 32pt @1x ship as ARGB rather than PNG; assert presence only.
    expect(icns.has('ic04'), 'missing ic04 (16pt — menu bar, Cmd-Tab)').toBe(true);
    expect(icns.has('ic05'), 'missing ic05 (32pt — Finder list view)').toBe(true);
  });

  it.each(ICNS_PNG_MEMBERS)('%s decodes at the documented size (%d px) — %s', async (type, size) => {
    const geometry = await measure(icns.get(type)!);
    expect([geometry.width, geometry.height]).toEqual([size, size]);
  });

  it.each(ICNS_PNG_MEMBERS)(
    '%s has fully transparent corners so the Dock shows a rounded icon, not a tile',
    async (type) => {
      const { cornerAlpha } = await measure(icns.get(type)!);
      expect(cornerAlpha).toEqual([0, 0, 0, 0]);
    }
  );

  it.each(ICNS_PNG_MEMBERS)('%s reserves the Apple grid margin so it matches neighbouring Dock icons', async (type) => {
    const { bodyFraction } = await measure(icns.get(type)!);
    expect(bodyFraction).toBeGreaterThan(APPLE_BODY_FRACTION - BODY_FRACTION_TOLERANCE);
    expect(bodyFraction).toBeLessThan(APPLE_BODY_FRACTION + BODY_FRACTION_TOLERANCE);
  });
});

describe('macOS dev icon', () => {
  it('follows the same Apple grid as the packaged icon', async () => {
    // Used for the unpackaged app on macOS and Linux (`src/index.ts`), where a
    // full-bleed icon would look wrong for exactly the same reason.
    const geometry = await measure(asset('resources/app_dev.png'));
    expect([geometry.width, geometry.height]).toEqual([1024, 1024]);
    expect(geometry.cornerAlpha).toEqual([0, 0, 0, 0]);
    expect(geometry.bodyFraction).toBeCloseTo(APPLE_BODY_FRACTION, 2);
  });
});

describe('full-bleed icons', () => {
  it.each(FULL_BLEED)('%s is %d px and edge-to-edge — %s', async (rel, size) => {
    const geometry = await measure(asset(rel));
    expect([geometry.width, geometry.height]).toEqual([size, size]);
    expect(geometry.bodyFraction).toBe(1);
  });

  it.each(FULL_BLEED)('%s still has transparent corners', async (rel) => {
    const { cornerAlpha, transparentRatio } = await measure(asset(rel));
    expect(cornerAlpha).toEqual([0, 0, 0, 0]);
    // A rounded square leaves r²(4−π) transparent per corner. Anything near
    // zero means the rounding was flattened away; anything large means the
    // artwork shrank inside its canvas.
    expect(transparentRatio).toBeGreaterThan(0.01);
    expect(transparentRatio).toBeLessThan(0.06);
  });
});

describe('Windows .ico', () => {
  const ico = readFileSync(asset('resources/app.ico'));

  it('is a well-formed icon directory', () => {
    expect(ico.readUInt16LE(0)).toBe(0); // reserved
    expect(ico.readUInt16LE(2)).toBe(1); // type: icon
  });

  it('carries the sizes Windows selects between, including 256 px for high-DPI', () => {
    const count = ico.readUInt16LE(4);
    const sizes = Array.from({ length: count }, (_, i) => ico[6 + i * 16] || 256).toSorted((a, b) => a - b);
    for (const required of [16, 24, 32, 48, 64, 128, 256]) {
      expect(sizes, `missing ${required}px entry`).toContain(required);
    }
  });
});

describe('macOS tray templates', () => {
  const TEMPLATES: Array<[string, number]> = [
    ['resources/trayTemplate.png', 16],
    ['resources/trayTemplate@2x.png', 32],
  ];

  it.each(TEMPLATES)('%s is %d px', async (rel, size) => {
    const { width, height } = await measure(asset(rel));
    expect([width, height]).toEqual([size, size]);
  });

  it.each(TEMPLATES)('%s is alpha-only, which is what makes it a template', async (rel) => {
    // macOS reads only the alpha of a template image and paints it itself. Any
    // colour left in the file is a sign the app icon was used by mistake.
    const { data } = await sharp(asset(rel)).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    let coloured = 0;
    for (let i = 0; i < data.length; i += 4) {
      if (data[i] !== 0 || data[i + 1] !== 0 || data[i + 2] !== 0) coloured++;
    }
    expect(coloured).toBe(0);
  });

  it.each(TEMPLATES)('%s carries the glyph alone, not the full icon', async (rel) => {
    // The full icon is edge-to-edge; the glyph leaves a margin and is mostly
    // transparent. Both numbers move sharply if the wrong source is used.
    const { bodyFraction, transparentRatio } = await measure(asset(rel));
    expect(bodyFraction).toBeGreaterThan(0.7);
    expect(bodyFraction).toBeLessThan(0.9);
    expect(transparentRatio).toBeGreaterThan(0.9);
  });
});

describe('artwork integrity', () => {
  /**
   * The cream field is part of the icon, not a background. An earlier revision
   * decomposed the artwork — extracting the glyph and redrawing it on the body
   * colour — which silently discarded it. These assert the artwork survives
   * whole, so a future "cleanup" cannot quietly crop it again.
   */
  const CREAM: [number, number, number] = [242, 239, 229];
  const NEAR = 6;

  it('keeps the cream field on the macOS icon, inset from the Apple margin', async () => {
    const { data, info } = await sharp(asset('resources/app_dev.png'))
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    const at = (x: number, y: number) => {
      const i = (y * info.width + x) * info.channels;
      return [data[i], data[i + 1], data[i + 2], data[i + 3]];
    };
    // 10% down the canvas is inside the body (which starts at ~9.8%) but well
    // above the dark square, so it must be cream and fully opaque.
    const [r, g, b, a] = at(Math.round(info.width / 2), Math.round(info.height * 0.1));
    expect(a).toBe(255);
    expect(Math.abs(r - CREAM[0])).toBeLessThan(NEAR);
    expect(Math.abs(g - CREAM[1])).toBeLessThan(NEAR);
    expect(Math.abs(b - CREAM[2])).toBeLessThan(NEAR);
  });

  it('keeps the dark panel proportional to the artwork, not stretched to the body', async () => {
    // Decomposing and redrawing would push the dark panel out to the full body.
    // Scaling the artwork whole keeps it at the proportion the designer drew.
    const { data, info } = await sharp(asset('resources/app_dev.png'))
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    const mid = Math.floor(info.height / 2);
    let first = -1;
    let last = -1;
    for (let x = 0; x < info.width; x++) {
      const i = (mid * info.width + x) * info.channels;
      if (data[i] < 80 && data[i + 3] > 200) {
        if (first < 0) first = x;
        last = x;
      }
    }
    const fraction = (last - first + 1) / info.width;
    expect(fraction).toBeGreaterThan(0.6);
    expect(fraction).toBeLessThan(0.7);
  });
});

describe('generator', () => {
  it('keeps the source artwork the icons are derived from', () => {
    // Without it the icons cannot be regenerated and drift becomes permanent.
    expect(existsSync(asset('resources/brand/nexwork-source-1024.png'))).toBe(true);
    expect(existsSync(asset('scripts/generate-brand-icons.mjs'))).toBe(true);
  });
});
